language: cpp

env: 	

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - ccache
    - g++-7
    - g++-9
    
script: 
    - cd /home/travis/build/kwikius/pqs/test
    - make gcc9_concepts_cpp2a
    - make clean
    - cd ./compile_fail
    - make
    - make clean
